name: Call Reusable Hello World

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  call-hello:
    uses: admsallai/StarsIndustries/.github/workflows/renotest.yaml@v1
    secrets: inherit
